version: "3"
services:
  frontend:
    image: vicsera/skainet:frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 4200:80
  backend:
    image: vicsera/skainet:backend
    container_name: backend
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: victor
      MYSQL_PASSWORD: 123
    ports:
      - 8080:8080
  db:
    image: mariadb
    container_name: database
    ports:
      - 3306:3306
    volumes:
      - /home/docker/data:/data
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: skainet
      MYSQL_USER: victor
      MYSQL_PASSWORD: 123
