version: "3"
services:
  backend:
    image: skainet-backend
    container_name: backend
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: victor
      MYSQL_PASSWORD: 123
    ports:
      - 8086:8086
  db:
    image: mariadb
    container_name: database
    ports:
      - 6033:3306
#    volumes:
#      - /home/docker/data:/data
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: skainet
      MYSQL_USER: victor
      MYSQL_PASSWORD: 123
  visualizer:
    image: dockersamples/visualizer:stable
    container_name: visualizer
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]